services:
  - type: web
    name: food-donation
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn food_donation.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: food_donation_db
          property: connectionString

databases:
  - name: food_donation_db
    databaseName: food_donation
    user: food_donation
    plan: free
